sudo: require

dist: xenial

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install fonts-font-awesome
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH

install:
  - sh ./texlive_install.sh

before_script:
  - sudo cp ./fonts/FontAwesome.ttf /usr/local/share/fonts/truetype/
  - sudo chown root /usr/local/share/fonts/truetype/FontAwesome.ttf
  - fc-cache

script:
  - make cv.pdf

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

branches:
  only:
    - new

notifications:
  email:
    recipients:
      - hatim@hatimak.me
    on_success: change
    on_failure: always

