sudo: require

dist: xenial

before_install:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH

install:
  - sh ./texlive_install.sh

before_script:
  - sudo cp ./fonts/* /usr/local/share/fonts/
  - sudo chown -R root /usr/local/share/fonts/*
  - fc-cache -fv

script:
  - make cv.pdf

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

branches:
  only:
    - new

notifications:
  email:
    recipients:
      - hatim@hatimak.me
    on_success: change
    on_failure: always

