sudo: require
dist: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq curl
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
install:
  - sh ./texlive_install.sh
before_script:
  - sudo cp ./fonts/* /usr/local/share/fonts/
  - sudo chown -R root /usr/local/share/fonts/*
  - fc-cache -fv
script:
  - make cv.pdf
after_success:
  - sh ./dropbox_uploader.sh upload cv.pdf /Documents/CV/CV-${TRAVIS_JOB_NUMBER}.pdf
  - sh ./dropbox_uploader.sh upload cv.pdf /Documents/CV/CV-latest.pdf
cache:
  directories:
    - "/tmp/texlive"
    - "$HOME/.texlive"
branches:
  only:
    - new
notifications:
  email:
    recipients:
      - hatim@hatimak.me
    on_success: change
    on_failure: always
env:
  matrix:
    secure: ENILyE6UBABVe4OWsrdQfGu5MoxrY2zWtSlpekgg01Fyj3w+f30/aihyWVGJ6p/9JzaOcERnny7TSoeoDShNzE+4a5E45JeIdGOJQ7XHXOP6iWeM13ZPtPQHjvPqgoSvkkX6tjDkCo3c5wjPlDDKEZO+DcyrmZef6WdPOt9Tk8JpoQSQh5e5EvUNF22VQ+iLePW/hDrIca5FBnVc1YVbPlsrfQ1n3CsRhz+ouH9zn8M7bPoCtZYdaNpuFAms108cHBV9V+IGdH9XI3LiDCYTcpnl6VOAq8LWOgSD4HyyfAbglMpm8HYJYLCTwYEqqS6mThDzTvjTee6+Ge35hpOy43uqmmxWh6EzUfiXSeYpxPYEODR4TCelV31IMnyUMp/cuxBF++UAW/RJTLuhs+XkepneiHHDx4uOxS9qVkCFBUyXuTKVJhEUpbUW57dLfBOstAqtHs1i8wJKqsYKm9crjcd77ZoNhnAh5MwT9PNbx4FT/gxEIeHQ46ImA5NL2B2j2M3RzbqFja80Qlt2yoFF8/uzje6uow+QxGPMXoUVD188iKnOXCACwI8addC2aCwSeKszbFfCEOsCH8QzqShw8bxRfyEM6FowJbpaff77CB5OVbU9hjwW7meUuZ0ppbX28/WPEPbLvWJhVRwEo07CDHBXKnkPE0myMQAqgGQa1ic=
