sudo: required

services: docker

script:
  - docker pull rekka/tectonic
  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind rekka/tectonic tectonic cv.tex

branches:
  only:
    - new

notifications:
  email:
    recipients:
      - hatim@hatimak.me
    on_success: change
    on_failure: always
